# ?? ? ??? application.yml? ??? ??????

spring:
  # 1. DB ?? ??
  datasource:
    # URL: 'team_project_db'? ?? "Forward Engineer"? ??? ?? ??? ?????.
    url: jdbc:mysql://localhost:3306/team_project_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Study1234! # (??? ? ??? ???? DB ????)
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. JPA (ORM) ??
  jpa:
    hibernate:
      # (????) Entity ??? ???? DB ???? '????' (?? ??? update)
      # ??? ?? JPA? ???? STUDY_HAS_CATEGORY ???? ?????.
      ddl-auto: update
    properties:
      hibernate:
        # (????) JPA? ???? SQL ???? ??? ??? ??? (??? ??)
        show_sql: true
        format_sql: true

# (??) ?? ?? ?? (??? 8080)
server:
  port: 8080